# Generated by Django 4.0.4 on 2022-05-30 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manufacturer', models.CharField(max_length=255)),
                ('Type', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Coupe', 'Coupe'), ('Hatchback', 'Hatchback'), ('Convertible', 'Convertible'), ('Crossover', 'Crossover'), ('Truck', 'Truck'), ('Van', 'Van'), ('Wagon', 'Wagon'), ('Other', 'Other')], max_length=13)),
                ('Model', models.CharField(max_length=100)),
                ('Specs', models.TextField()),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateField()),
                ('Seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
